### ISSUE TITLE
EGS .dat saves cannot be opened.

### ISSUE THREAD

**Issue by arty-s** [hypercyclist/snowrunner_save_editor#1]
Only .cfg filetype is supported.
![Screenshot 2024-01-05 154400](https://github.com/hypercyclist/snowrunner_save_editor/assets/101047901/fd0ae55a-178f-4dfd-b2c9-261db876f391)

**Comment by hypercyclist** [comment]
Hello. Thank you for reporting this. I checked latest windows app 1.02. I confirm your issue. Fixed in new version 1.03. 
https://github.com/hypercyclist/snowrunner_save_editor/releases/tag/Release-1.03
