### ISSUE TITLE
New maps missing

### ISSUE THREAD

**Issue by Guardempire** [hypercyclist/snowrunner_save_editor#2]
Hey mate, this is by far the best editor i could find! Only the new maps are missing, if i change something all progress on the new map is gone. Would be nice if you can fix it!

**Comment by hypercyclist** [comment]
> Hey mate, this is by far the best editor i could find! Only the new maps are missing, if i change something all progress on the new map is gone. Would be nice if you can fix it!

Okay. I will fix it in one-two days. The editor is abandoned. I rarely play the game. But adding new maps is not difficult for me.

**Comment by shishir-m** [comment]
Thanks looking forward to it. If I havent done the new maps will this work? (I just need 100% on the first map)

**Comment by hypercyclist** [comment]
> Thanks looking forward to it. If I havent done the new maps will this work? (I just need 100% on the first map)

Yes, it should work. I'm updating the editor right now. If I don't run into any problems along the way, it should be ready today.

**Comment by hypercyclist** [comment]
Fixed. Updated list of missions, trucks and upgrades. I checked. Added a little money to myself. Activated a couple of upgrades. It works. But I advise you to make a backup.

**Comment by Guardempire** [comment]
THX guys!!!!!!!
